### ISSUE TITLE
Pubblicare il link per i biglietti

### ISSUE THREAD

**Issue by Davmuz** [gdg-cloud-modena/devfest#1]
https://devfest-modena-2024.eventbrite.it/

**Comment by emilianomaccaferri** [comment]
@bavyhappy @carzacc riuscite a farlo?

**Comment by carzacc** [comment]
> @bavyhappy @carzacc riuscite a farlo?

Sulla landing?

**Comment by emilianomaccaferri** [comment]
> > [@bavyhappy](https://github.com/bavyhappy) [@carzacc](https://github.com/carzacc) riuscite a farlo?
> 
> Sulla landing?

yes
