### ISSUE TITLE
Correzioni per la pagina "speakers" e la pagina "team"

### ISSUE THREAD

**Issue by Davmuz** [gdg-cloud-modena/devfest#12]
![image](https://github.com/user-attachments/assets/43b1d5db-9bd5-48f7-9e0a-4b963cd69df5)

Da applicare sia alla pagina "speakers" che alla pagina "team":

1. Spazio eccessivo tra titolo e riga sotto. Impostare lo spazio alla stessa dimensione usata nella pagina dei singoli speaker.
2. Sfondo di colore diverso dalle altre pagine. Impostare il bianco puro.
3. Solo per la pagina "speakers": aggiungere l'introduzione (vedi sotto).

Introduzione:

> Durante questo evento, avrai l'opportunità di ascoltare e incontrare esperti del settore, innovatori e professionisti. Qui trovi tutte le informazioni sugli interventi in programma, con dettagli sugli argomenti trattati e i profili degli speaker che li presenteranno.
> 
> Esplora il programma, scopri le storie e le competenze di chi salirà sul palco e preparati a vivere un'esperienza di apprendimento e ispirazione senza pari a Modena.

NB: l'introduzione è in due paragrafi per cui ognuno va all'interno del proprio tag <p>.

**Comment by carzacc** [comment]
@Davmuz anche la pagina home non è bianco puro, queste pagine non sono bianco puro perché invece nel design si è optato per avere le card speaker/team in bianco puro, che quindi così risaltano/si distinguono
