### ISSUE TITLE
Cambiare le voci del footer

### ISSUE THREAD

**Issue by Davmuz** [gdg-cloud-modena/devfest#15]
Cambiare tutte le voci del footer, impostare i link anche se non portano ancora a nessuna pagina:

- FAQ -> /faq/
- Location -> /location/
- Sponsor -> /sponsors/
- Team -> /team/
- Comunità -> /communities/
- Contacts -> /contact-us/

Ancora più in basso, lasciare le seguenti ed impostare i link anche se non funzionano:

- Privacy policy -> /privacy/
- Note legali -> /legal/
- Codice di condotta -> /code-of-conduct/

Aggiungere link social, piccoli:

- LinkedIn -> https://www.linkedin.com/showcase/devfest-modena/
- Facebook -> https://www.facebook.com/events/7532786990157832/
- Instagram -> https://instagram.com/explore/tags/devfestmodena
- X -> https://x.com/hashtag/devfestmodena

Eliminare tutte le altre voci non indicate in questa issue.

**Comment by Grimos10** [comment]
Per impostare i link delle pagine ancora non fatte devo creare una pagina vuota? Perchè altrimenti se imposto il link ad una pagina non esistente nuxt dà warning e poi non ti fa compilare e deployare. Oppure un'altra soluzione sarebbe impostare il link delle pagine non esistenti a "/" che sarebbe la home
