### ISSUE TITLE
Caricamento speech e speaker - versione temporanea senza orari

### ISSUE THREAD

**Issue by Davmuz** [gdg-cloud-modena/devfest#8]
Al momento non abbiamo ancora orari e sale per cui potete procedere con una semplice pagina di lista con le relative pagine di dettaglio.

Gli speaker da caricare si trovano nella cartella ["website / speakers"](https://drive.google.com/drive/folders/1GC2h2iKXfphUQPajzY36xggIRS1AmcRO?usp=drive_link). Nel file ["Speakers DevFest"](https://docs.google.com/spreadsheets/d/1_a0YSrw4p5NuoIgk76v3OP1wsZBarKZUcqTHo9wGrCw/edit?usp=sharing) ci sono i dettagli da pubblicare nella scheda.

L'ordine di caricamento è quello del file.

Va pubblicato solo il link indicato nel file, non quelli eventualmente presenti nella descrizione.

**Comment by carzacc** [comment]
@Davmuz magari si potevano togliere dal doc gli altri link per evitare problemi

**Comment by Davmuz** [comment]
Ragionavo solo sull'elenco, ma va bene così. Pubblichiamo anche gli altri link nella bio. THX
